import { Hotel, InquiryLead } from "./types";

export const INITIAL_HOTELS: Hotel[] = [
  {
    id: "polo-orchid-resort",
    name: "Polo Orchid Resort",
    slug: "polo-orchid-resort-cherrapunji",
    tagline: "Perched atop the misty valley overlooking the majestic Seven Sisters Falls",
    starRating: 5,
    pricePerNight: 8500,
    originalPrice: 10500,
    area: "Nohsngithiang",
    address: "Mawsmai, Mawmluh-Cherrapunjee Road, Sohra, Meghalaya 793108",
    coordinates: { lat: 25.2638, lng: 91.7289 },
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: true,
    status: "active",
    rating: 4.9,
    reviewsCount: 284,
    amenities: [
      "Infinity View Pool",
      "Free High-Speed Wi-Fi",
      "Seven Sisters Viewpoint",
      "Fine Dining Restaurant",
      "Bonfire Nights",
    ],
    rooms: [
      {
        id: "r1",
        name: "Valley View Luxury Villa",
        price: 8500,
        originalPrice: 10500,
        capacity: "2 Adults",
        beds: "1 King Bed",
        features: ["Canyon View", "Balcony"],
      },
      {
        id: "r2",
        name: "Presidential Mist Suite",
        price: 13500,
        originalPrice: 16000,
        capacity: "4 Adults",
        beds: "2 King Beds",
        features: ["180° Waterfall View", "Jacuzzi"],
      },
    ],
    description: "Cliffside luxury resort with front-row views of Seven Sisters Falls.",
    highlights: ["Front-row cliff views", "Heated pool", "Curated treks"],
    checkInTime: "14:00",
    checkOutTime: "11:00",
    phone: "+91 87947 12345",
    email: "bookings@cherrapunjistays.com",
  },
  {
    id: "jiva-resort",
    name: "Jiva Resort Cherrapunji",
    slug: "jiva-resort-cherrapunji",
    tagline: "Eco-luxury retreat amidst tranquil pine groves and dancing clouds",
    starRating: 4,
    pricePerNight: 6200,
    originalPrice: 7500,
    area: "Saitsohpen",
    address: "Saitsohpen, Lower Cherrapunjee, Sohra, Meghalaya 793108",
    coordinates: { lat: 25.2815, lng: 91.7192 },
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: true,
    status: "active",
    rating: 4.8,
    reviewsCount: 196,
    amenities: ["Free High-Speed Wi-Fi", "Rock Gardens", "Fireplace", "Travel Desk"],
    rooms: [
      {
        id: "r3",
        name: "Deluxe Pine Cottage",
        price: 6200,
        originalPrice: 7500,
        capacity: "2 Adults",
        beds: "1 Queen Bed",
        features: ["Garden View", "Rain Shower"],
      },
    ],
    description: "Eco-conscious stone resort in Saitsohpen.",
    highlights: ["Cedar stone cottages", "Local Khasi meals"],
    checkInTime: "13:00",
    checkOutTime: "11:00",
    phone: "+91 87947 12346",
    email: "jiva@cherrapunjistays.com",
  },
  {
    id: "cherrapunjee-holiday-resort",
    name: "Cherrapunjee Holiday Resort",
    slug: "cherrapunjee-holiday-resort",
    tagline: "The pioneering nature retreat for Living Root Bridges",
    starRating: 3,
    pricePerNight: 3800,
    originalPrice: 4500,
    area: "Laitkynsew",
    address: "Village Laitkynsew, Cherrapunjee, Meghalaya 793108",
    coordinates: { lat: 25.2158, lng: 91.6784 },
    images: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: true,
    status: "active",
    rating: 4.7,
    reviewsCount: 340,
    amenities: ["Root Bridge Treks", "Homecooked Food", "Free Wi-Fi", "Bonfire"],
    rooms: [
      {
        id: "r4",
        name: "Country Comfort Room",
        price: 3800,
        originalPrice: 4500,
        capacity: "2 Guests",
        beds: "1 Queen Bed",
        features: ["Mountain Air", "Hot Geyser"],
      },
    ],
    description: "The pioneer stay near Nongriat Living Root Bridges.",
    highlights: ["Guided hike access", "Warm family hospitality"],
    checkInTime: "12:00",
    checkOutTime: "10:30",
    phone: "+91 87947 12347",
    email: "holidayresort@cherrapunjistays.com",
  },
];

export const INITIAL_LEADS: InquiryLead[] = [
  {
    id: "lead-101",
    customerName: "Ananya Deshmukh",
    customerPhone: "+91 98201 44521",
    customerEmail: "ananya.d@gmail.com",
    hotelId: "polo-orchid-resort",
    hotelName: "Polo Orchid Resort",
    roomType: "Valley View Luxury Villa",
    checkIn: "2026-10-15",
    checkOut: "2026-10-18",
    guests: { adults: 2, children: 1 },
    specialRequests: "Anniversary celebration. Need cliff view room & airport cab.",
    status: "new",
    budget: 8500,
    notes: [],
    createdAt: "Just now",
  },
  {
    id: "lead-102",
    customerName: "Vikram Malhotra",
    customerPhone: "+91 98110 87654",
    customerEmail: "vikram.m@outlook.com",
    hotelId: "jiva-resort",
    hotelName: "Jiva Resort Cherrapunji",
    roomType: "Deluxe Pine Cottage",
    checkIn: "2026-10-20",
    checkOut: "2026-10-22",
    guests: { adults: 2, children: 0 },
    specialRequests: "Need quiet cottage away from reception.",
    status: "contacted",
    budget: 6200,
    notes: [
      {
        id: "n1",
        text: "Spoke with client on phone. Sent WhatsApp quotation with 10% advance details.",
        author: "Admin Desk",
        createdAt: "2 hours ago",
      },
    ],
    createdAt: "Today, 11:30 AM",
  },
  {
    id: "lead-103",
    customerName: "Rohan & Priyam Chatterjee",
    customerPhone: "+91 94330 19283",
    customerEmail: "rohan.chat@yahoo.in",
    hotelId: "cherrapunjee-holiday-resort",
    hotelName: "Cherrapunjee Holiday Resort",
    roomType: "Country Comfort Room",
    checkIn: "2026-11-02",
    checkOut: "2026-11-05",
    guests: { adults: 4, children: 0 },
    specialRequests: "Trekking guide needed for Double Decker living root bridge.",
    status: "quote_sent",
    budget: 3800,
    notes: [
      {
        id: "n2",
        text: "Sent customized 3-day trek itinerary with guide fee included.",
        author: "Trek Desk",
        createdAt: "Yesterday",
      },
    ],
    createdAt: "Yesterday, 04:15 PM",
  },
  {
    id: "lead-104",
    customerName: "Kavita Nair",
    customerPhone: "+91 97420 55671",
    customerEmail: "kavita.nair@techcorp.com",
    hotelId: "polo-orchid-resort",
    hotelName: "Polo Orchid Resort",
    roomType: "Presidential Mist Suite",
    checkIn: "2026-10-10",
    checkOut: "2026-10-13",
    guests: { adults: 4, children: 0 },
    specialRequests: "Confirmed booking with 50% deposit received.",
    status: "converted",
    budget: 13500,
    notes: [
      {
        id: "n3",
        text: "Advance payment of ₹20,000 received via UPI. Voucher emailed.",
        author: "Admin Desk",
        createdAt: "3 days ago",
      },
    ],
    createdAt: "3 days ago",
  },
];
